# Filename: /Users/krishna/github/dotfiles-public/starship-config/starship.toml
# https://starship.rs/config/#git-branch

# # In case you want to modify the order of the items you can do this
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_status\
# $git_commit\
# $git_state\
# $all\
# $time\
# $character
# """

# This will show the time on a 2nd line
format = """
$all\
$time\
$character
"""

[battery]
disabled = true

[gcloud]
disabled = true

[time]
style = '#a6aaf1 bold'
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'

[username]
style_user = '#a6aaf1 bold'
style_root = 'white bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[@](white bold)[$hostname](#50fa7b bold)'

[directory]
style = '#00a5ff bold'
truncation_length = 0
truncate_to_repo = false

